site_name: utau.info
nav:
  - Home: index.md
  - Starting UTAU: 
    - Start:
      - Introduction: start/intro.md
      - Glossary: start/glossary.md
    - Setup:
      - Installation: start/install.md
  - Resources:
    - General: resources/general.md 
    - Resamplers: resources/resamplers.md
    - Wavtools: resources/wavtools.md
    - Plugins: resources/plugins.md
    - Tools: resources/tools.md
  - About: about.md
  - To-do: todo.md
theme:
  name: material
  icon:
    logo: material/music-note
  features:
    - navigation.tabs
    - navigation.sections
  palette: 
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate 
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 