site_name: utau.info
site_url: https://utau.info
nav:
  - Home: 
    - index.md
    - Changelog: changelog.md
  - Starting UTAU: 
    - Start:
      - Introduction: start/intro.md
      - Glossary: start/glossary.md
    - Setup:
      - Installation: start/install.md
      - Resamplers: start/resamplers.md
      - Plugins: start/plugins.md
    - Voicebanks:
      - Types: start/vbtypes.md
      - Downloading: start/vbdownload.md
      - Loading: start/vbloading.md
    - USTs:
      - Adding Notes: start/ustcreation.md
      - Flags: start/flags.md
      - Tuning: start/tuning.md
  - Resources:
    - General: resources/general.md 
    - Resamplers: resources/resamplers.md
    - Wavtools: resources/wavtools.md
    - Plugins: resources/plugins.md
    - Tools: resources/tools.md
    - Reclists: 
      - resources/reclists/index.md
      - Japanese: resources/reclists/japanese.md
#      - Chinese: resources/reclists/chinese.md
#      - Korean: resources/reclists/korean.md
      - English: resources/reclists/english.md
  - About: about.md
theme:
  name: material
  favicon: ../img/favicon.png
  icon:
    logo: material/music-note
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
  palette: 
    - scheme: slate 
      primary: deep purple
      accent: purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
plugins:
  - tags 
  - search 
  - blog
  - social