site_name: Test docs
site_description: 'A docs test'
site_author: 'nagotown'
docs_dir: docs/
repo_name: 'nagotown/webtest2'
repo_url: 'https://github.com/nagotown/webtest2'
nav:
    - Home: index.md
    - About: about.md
    - Starting: start.md

