name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version:  3.x
      - run: pip install mkdocs-material
      - run: pip install "mkdocs-material[imaging]"
      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish docs
        run: mkdocs gh-deploy --force
